# Chapter 2 Exercises



## Exercise 1

### Setup

In [3]:
import numpy as np
import pandas as pd

### Download data

In [4]:
from pathlib import Path
import tarfile
import urllib.request

def load_housing_data():
    tarball_path = Path("datasets/housing.tgz")
    if not tarball_path.is_file():
        Path("datasets").mkdir(parents=True, exist_ok=True)
        url = "https://github.com/ageron/data/raw/main/housing.tgz"
        urllib.request.urlretrieve(url, tarball_path)
        with tarfile.open(tarball_path) as housing_tarball:
            housing_tarball.extractall(path="datasets", filter="data")
    return pd.read_csv(Path("datasets/housing/housing.csv"))

housing_full = load_housing_data()

In [5]:
housing_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [6]:
housing_full.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

### Split data - training and validation

In [7]:
housing_full['income_cat'] = pd.cut(
    housing_full['median_income'],
    bins=[0., 1.5, 3.0, 4.5, 6.0, np.inf],
    labels=[1, 2, 3, 4, 5])

In [8]:
from sklearn.model_selection import train_test_split

strat_train_set, strat_test_set = train_test_split(
  housing_full,
  test_size=0.2,
  random_state=42,
  stratify=housing_full['income_cat'])

In [9]:
housing_full['income_cat'].value_counts() / len(housing_full)

income_cat
3    0.350581
2    0.318847
4    0.176308
5    0.114438
1    0.039826
Name: count, dtype: float64

In [10]:
strat_test_set['income_cat'].value_counts() / len(strat_test_set)

income_cat
3    0.350533
2    0.318798
4    0.176357
5    0.114341
1    0.039971
Name: count, dtype: float64

In [11]:
# Not using income_cat anymore - already stratified
# Remove so data is back to original state
for set_ in (strat_train_set, strat_test_set):
    # Code might not run in order, ensure column exists
    if ("income_cat" in set_.columns):
        set_.drop("income_cat", axis=1, inplace=True)

housing = strat_train_set.drop("median_house_value", axis=1)
housing_labels = strat_train_set["median_house_value"].copy()

### Define pipeline

Define transformation pipelines to prepare the data for machine learning.

In [12]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.cluster import KMeans
from sklearn.metrics.pairwise import rbf_kernel

class ClusterSimilarity(BaseEstimator, TransformerMixin):
    """
    Find similar clusters using RBF kernel based on KMeans cluster centers.
    """
    def __init__(self, n_clusters=10, gamma=1.0, random_state=None):
        self.n_clusters = n_clusters
        self.gamma = gamma
        self.random_state = random_state

    def fit(self, X, y=None, sample_weight=None):
        self.kmeans_ = KMeans(self.n_clusters, random_state=self.random_state)
        self.kmeans_.fit(X, sample_weight=sample_weight)
        return self  # always return self!

    def transform(self, X):
        return rbf_kernel(X, self.kmeans_.cluster_centers_, gamma=self.gamma)

    def get_feature_names_out(self, names=None):
        return [f"Cluster {i} similarity" for i in range(self.n_clusters)]

In [13]:
from sklearn.compose import ColumnTransformer, make_column_selector
from sklearn.preprocessing import FunctionTransformer, OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.pipeline import make_pipeline
from sklearn import set_config

# Show the pipeline diagram
set_config(display='diagram')

def column_ratio(X):
    """
    Calculate the ratio between the first and second columns of a 2D array.

    Args:
        X: A 2D numpy array or matrix with at least 2 columns.

    Returns:
        numpy.ndarray: A 2D array containing the element-wise ratio of
                       column 0 divided by column 1.
    """
    return X[:, [0]] / X[:, [1]]

def ratio_name(function_transformer, feature_names_in):
    return ["ratio"] # feature names out

def ratio_pipeline():
    return make_pipeline(
        SimpleImputer(strategy="median"),
        FunctionTransformer(column_ratio, feature_names_out=ratio_name),
        StandardScaler())

log_pipeline = make_pipeline(
    SimpleImputer(strategy="median"),
    FunctionTransformer(np.log, feature_names_out="one-to-one"),
    StandardScaler())

cat_pipeline = make_pipeline(
    SimpleImputer(strategy="most_frequent"),
    OneHotEncoder(handle_unknown="ignore"))

cluster_simil = ClusterSimilarity(n_clusters=10, gamma=1., random_state=42)
default_num_pipeline = make_pipeline(SimpleImputer(strategy="median"),
                                     StandardScaler())

preprocessing = ColumnTransformer([
        ("bedrooms", ratio_pipeline(), ["total_bedrooms", "total_rooms"]),
        ("rooms_per_house", ratio_pipeline(), ["total_rooms", "households"]),
        ("people_per_house", ratio_pipeline(), ["population", "households"]),
        ("log", log_pipeline, ["total_bedrooms", "total_rooms", "population",
                            "households", "median_income"]),
        ("geo", cluster_simil, ["latitude", "longitude"]),
        ("cat", cat_pipeline, make_column_selector(dtype_include="object")),
    ],
    remainder=default_num_pipeline)

preprocessing


ColumnTransformer(remainder=Pipeline(steps=[('simpleimputer',
                                             SimpleImputer(strategy='median')),
                                            ('standardscaler',
                                             StandardScaler())]),
                  transformers=[('bedrooms',
                                 Pipeline(steps=[('simpleimputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('functiontransformer',
                                                  FunctionTransformer(feature_names_out=<function ratio_name at 0x116402200>,
                                                                      func=<function column_ratio at 0...
                                 ['total_bedrooms', 'total_rooms', 'population',
                                  'households', 'median_income']),
                                ('geo', ClusterSimilarity(random_state=42),
                                 ['latitude', 'longitude']),
                                ('cat',
                                 Pipeline(steps=[('simpleimputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('onehotencoder',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 <sklearn.compose._column_transformer.make_column_selector object at 0x115f478c0>)])

### Transform data

In [14]:
housing_prepared = preprocessing.fit_transform(housing)
housing_prepared.shape

# Code might not run in order, so adding this assertion to ensure correctness
assert housing_prepared.shape == (16512, 24)

In [15]:
# Get a glimpse of the transformed data
pd.DataFrame(housing_prepared, columns=preprocessing.get_feature_names_out()).head(10)

bedrooms__ratio  rooms_per_house__ratio  people_per_house__ratio  \
0         1.846624               -0.866027                -0.330204   
1        -0.508121                0.024550                -0.253616   
2        -0.202155               -0.041193                -0.051041   
3        -0.149006               -0.034858                -0.141475   
4         0.963208               -0.666554                -0.306148   
5        -0.743942                0.113646                -0.184066   
6        -0.489249                0.556477                 0.050602   
7        -0.389217               -0.024225                -0.158161   
8         0.675013               -0.456707                 0.128117   
9         1.816054               -0.941470                -0.044126   

   log__total_bedrooms  log__total_rooms  log__population  log__households  \
0             1.324114          0.637892         0.456906         1.310369   
1            -0.252671         -0.063576        -0.711654        -0.142030   
2            -0.925266         -0.859927        -0.941997        -0.913030   
3             0.952773          0.943475         0.670700         0.925373   
4             1.437622          1.003590         0.719093         1.481464   
5            -0.475568         -0.159448        -0.655784        -0.295737   
6            -1.058155         -0.856230        -1.076379        -1.255299   
7             1.029712          1.126642         0.806339         1.105551   
8             0.905123          0.580740         1.167537         0.864504   
9             0.406790         -0.246253         0.468905         0.492199   

   log__median_income  geo__Cluster 0 similarity  geo__Cluster 1 similarity  \
0           -1.071522               4.581829e-01               1.241847e-14   
1            1.194712               6.511495e-10               9.579596e-01   
2           -0.756981               3.432506e-01               4.261141e-15   
3           -0.912253               2.244844e-15               2.704823e-01   
4            0.034537               1.090228e-11               9.422206e-01   
5           -0.078518               6.423987e-01               1.159386e-11   
6            1.203677               8.006474e-11               9.595991e-01   
7            0.942136               7.868544e-01               2.160931e-12   
8           -0.498515               2.807941e-09               8.685613e-01   
9           -2.283376               7.083722e-11               9.876226e-01   

   ...  geo__Cluster 6 similarity  geo__Cluster 7 similarity  \
0  ...               8.489216e-04               9.770322e-01   
1  ...               5.614049e-27               1.260964e-13   
2  ...               5.641131e-03               7.303265e-01   
3  ...               5.913326e-35               5.201263e-20   
4  ...               5.421817e-30               1.048030e-15   
5  ...               1.543061e-04               3.632806e-01   
6  ...               1.139000e-28               1.111420e-14   
7  ...               6.336028e-05               7.521653e-01   
8  ...               7.934107e-26               7.053833e-13   
9  ...               1.915751e-28               9.000955e-15   

   geo__Cluster 8 similarity  geo__Cluster 9 similarity  \
0               2.382191e-08               3.819126e-18   
1               1.103491e-01               3.547610e-01   
2               2.508224e-08               2.669659e-18   
3               1.712982e-03               8.874598e-01   
4               2.568824e-02               5.279506e-01   
5               8.154546e-06               2.324587e-14   
6               4.431923e-02               3.744913e-01   
7               8.513323e-07               1.114788e-15   
8               1.824289e-01               2.873697e-01   
9               6.364003e-02               5.620424e-01   

   cat__ocean_proximity_<1H OCEAN  cat__ocean_proximity_INLAND  \
0                             0.0                          0.0   
1    

In [16]:
preprocessing.get_feature_names_out()

array(['bedrooms__ratio', 'rooms_per_house__ratio',
       'people_per_house__ratio', 'log__total_bedrooms',
       'log__total_rooms', 'log__population', 'log__households',
       'log__median_income', 'geo__Cluster 0 similarity',
       'geo__Cluster 1 similarity', 'geo__Cluster 2 similarity',
       'geo__Cluster 3 similarity', 'geo__Cluster 4 similarity',
       'geo__Cluster 5 similarity', 'geo__Cluster 6 similarity',
       'geo__Cluster 7 similarity', 'geo__Cluster 8 similarity',
       'geo__Cluster 9 similarity', 'cat__ocean_proximity_<1H OCEAN',
       'cat__ocean_proximity_INLAND', 'cat__ocean_proximity_ISLAND',
       'cat__ocean_proximity_NEAR BAY', 'cat__ocean_proximity_NEAR OCEAN',
       'remainder__housing_median_age'], dtype=object)

### Select model

In [17]:
from sklearn.svm import SVR

svr = SVR(kernel="rbf", C=0.1)
svm_regressor = make_pipeline(preprocessing, svr)
svm_regressor.fit(housing, housing_labels)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder=Pipeline(steps=[('simpleimputer',
                                                              SimpleImputer(strategy='median')),
                                                             ('standardscaler',
                                                              StandardScaler())]),
                                   transformers=[('bedrooms',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('functiontransformer',
                                                                   FunctionTransformer(feature_names_out=<function ratio_name at 0x116...
                                                   'total_rooms', 'population',
                                                   'households',
                                                   'median_income']),
                                                 ('geo',
                                                  ClusterSimilarity(random_state=42),
                                                  ['latitude', 'longitude']),
                                                 ('cat',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehotencoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  <sklearn.compose._column_transformer.make_column_selector object at 0x115f478c0>)])),
                ('svr', SVR(C=0.1))])

### Predictions - first attempt

In [18]:
housing_predictions = svm_regressor.predict(housing).round(-2) # round to nearest hundred
housing_predictions[:5]


array([179200., 179300., 179100., 179100., 179200.])

In [19]:
housing_labels.iloc[:5]

13096    458300.0
14973    483800.0
3785     101700.0
14689     96100.0
20507    361800.0
Name: median_house_value, dtype: float64

Predictions are quite bad!

In [20]:
from sklearn.metrics import root_mean_squared_error
svm_rmse = root_mean_squared_error(housing_labels, housing_predictions)
svm_rmse

118414.95118392352

### Fine tune the model

WARNING: This cell may take a long time to run.

In [21]:
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline

full_pipeline = Pipeline([
    ('preprocessing', preprocessing),
    ('svr', SVR(kernel="linear", C=1.0))
])

param_grid = [
    {
        'svr__kernel': ['linear'],
        'svr__C': [0.1, 1.0, 10.0]
    },
    {
        'svr__kernel': ['rbf'],
        'svr__C': [0.1, 1.0, 10.0],
        'svr__gamma': [0.01, 0.1, 1.0]
    }
]

grid_search = GridSearchCV(full_pipeline, param_grid, cv=3,
                           scoring='neg_root_mean_squared_error')

# May take a long time to run
# Training on a subset to speed up
grid_search.fit(housing[:5000], housing_labels[:5000])

GridSearchCV(cv=3,
             estimator=Pipeline(steps=[('preprocessing',
                                        ColumnTransformer(remainder=Pipeline(steps=[('simpleimputer',
                                                                                     SimpleImputer(strategy='median')),
                                                                                    ('standardscaler',
                                                                                     StandardScaler())]),
                                                          transformers=[('bedrooms',
                                                                         Pipeline(steps=[('simpleimputer',
                                                                                          SimpleImputer(strategy='median')),
                                                                                         ('functiontransformer',
                                                                                          FunctionTransformer(feature_names_out=<f...
                                                                                         ('onehotencoder',
                                                                                          OneHotEncoder(handle_unknown='ignore'))]),
                                                                         <sklearn.compose._column_transformer.make_column_selector object at 0x115f478c0>)])),
                                       ('svr', SVR(kernel='linear'))]),
             param_grid=[{'svr__C': [0.1, 1.0, 10.0],
                          'svr__kernel': ['linear']},
                         {'svr__C': [0.1, 1.0, 10.0],
                          'svr__gamma': [0.01, 0.1, 1.0],
                          'svr__kernel': ['rbf']}],
             scoring='neg_root_mean_squared_error')

In [22]:
grid_search.best_params_

{'svr__C': 10.0, 'svr__kernel': 'linear'}

In [23]:
cv_res = pd.DataFrame(grid_search.cv_results_)
cv_res.sort_values(by="mean_test_score", ascending=False, inplace=True)
cv_res.head()

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
2        0.458638      0.016778         0.164493        0.000115   
1        0.472553      0.015903         0.189728        0.027588   
10       0.921077      0.206202         0.582212        0.072469   
9        0.668872      0.001899         0.489650        0.001001   
0        0.463979      0.015921         0.166227        0.002473   

    param_svr__C param_svr__kernel  param_svr__gamma  \
2           10.0            linear               NaN   
1            1.0            linear               NaN   
10          10.0               rbf              0.10   
9           10.0               rbf              0.01   
0            0.1            linear               NaN   

                                               params  split0_test_score  \
2           {'svr__C': 10.0, 'svr__kernel': 'linear'}     -106135.817586   
1            {'svr__C': 1.0, 'svr__kernel': 'linear'}     -118501.271743   
10  {'svr__C': 10.0, 'svr__gamma': 0.1, 'svr__kern...     -119529.986427   
9   {'svr__C': 10.0, 'svr__gamma': 0.01, 'svr__ker...     -120070.397317   
0            {'svr__C': 0.1, 'svr__kernel': 'linear'}     -120211.660829   

    split1_test_score  split2_test_score  mean_test_score  std_test_score  \
2      -107064.824543     -102000.759713   -105067.133947     2201.174185   
1      -120584.513069     -114515.902573   -117867.229128     2517.739180   
10     -121724.044917     -115424.423964   -118892.818436     2610.975977   
9      -122306.634420     -115985.509091   -119454.180276     2617.116599   
0      -122451.442870     -116096.798901   -119586.634200     2631.649509   

    rank_test_score  
2                 1  
1                 2  
10                3  
9                 4  
0                 5

In [24]:
housing_predictions = grid_search.predict(housing.iloc[:5])
housing_predictions[:5]

array([179037.33679453, 225831.0205717 , 149619.53837431, 155044.95479993,
       200373.05755343])

In [25]:
housing_labels[:5]

13096    458300.0
14973    483800.0
3785     101700.0
14689     96100.0
20507    361800.0
Name: median_house_value, dtype: float64

### Model answer

In [26]:
# Retry with model answer
param_grid = [
        {'svr__kernel': ['linear'], 'svr__C': [10., 30., 100., 300., 1000.,
                                               3000., 10000., 30000.0]},
        {'svr__kernel': ['rbf'], 'svr__C': [1.0, 3.0, 10., 30., 100., 300.,
                                            1000.0],
         'svr__gamma': [0.01, 0.03, 0.1, 0.3, 1.0, 3.0]},
    ]

svr_pipeline = Pipeline([("preprocessing", preprocessing), ("svr", SVR())])
grid_search = GridSearchCV(svr_pipeline, param_grid, cv=3,
                           scoring='neg_root_mean_squared_error')
grid_search.fit(housing.iloc[:5000], housing_labels.iloc[:5000])

GridSearchCV(cv=3,
             estimator=Pipeline(steps=[('preprocessing',
                                        ColumnTransformer(remainder=Pipeline(steps=[('simpleimputer',
                                                                                     SimpleImputer(strategy='median')),
                                                                                    ('standardscaler',
                                                                                     StandardScaler())]),
                                                          transformers=[('bedrooms',
                                                                         Pipeline(steps=[('simpleimputer',
                                                                                          SimpleImputer(strategy='median')),
                                                                                         ('functiontransformer',
                                                                                          FunctionTransformer(feature_names_out=<f...
                                                                         <sklearn.compose._column_transformer.make_column_selector object at 0x115f478c0>)])),
                                       ('svr', SVR())]),
             param_grid=[{'svr__C': [10.0, 30.0, 100.0, 300.0, 1000.0, 3000.0,
                                     10000.0, 30000.0],
                          'svr__kernel': ['linear']},
                         {'svr__C': [1.0, 3.0, 10.0, 30.0, 100.0, 300.0,
                                     1000.0],
                          'svr__gamma': [0.01, 0.03, 0.1, 0.3, 1.0, 3.0],
                          'svr__kernel': ['rbf']}],
             scoring='neg_root_mean_squared_error')

In [36]:
housing_predictions = grid_search.predict(housing.iloc[:5])
housing_predictions[:5]

array([254014.07049211, 332683.64627887, 109831.47471049, 101464.4792938 ,
       306739.39968746])

In [37]:
svr_grid_search_rmse = -grid_search.best_score_
svr_grid_search_rmse

np.float64(70059.92772805203)

In [29]:
grid_search.best_params_

{'svr__C': 10000.0, 'svr__kernel': 'linear'}

Best parameter value of C was 10,000 which was the maximum, we should try again with higher C values.

## Exercise 2



In [30]:
from sklearn.model_selection import RandomizedSearchCV

rnd_search = RandomizedSearchCV(
    svr_pipeline,
    param_distributions=param_grid,
    n_iter=10,
    cv=3,
    scoring='neg_root_mean_squared_error',
    random_state=42
)

rnd_search.fit(housing.iloc[:5000], housing_labels.iloc[:5000])

RandomizedSearchCV(cv=3,
                   estimator=Pipeline(steps=[('preprocessing',
                                              ColumnTransformer(remainder=Pipeline(steps=[('simpleimputer',
                                                                                           SimpleImputer(strategy='median')),
                                                                                          ('standardscaler',
                                                                                           StandardScaler())]),
                                                                transformers=[('bedrooms',
                                                                               Pipeline(steps=[('simpleimputer',
                                                                                                SimpleImputer(strategy='median')),
                                                                                               ('functiontransformer',
                                                                                                FunctionTransformer(feature_names_...
                                                                               <sklearn.compose._column_transformer.make_column_selector object at 0x115f478c0>)])),
                                             ('svr', SVR())]),
                   param_distributions=[{'svr__C': [10.0, 30.0, 100.0, 300.0,
                                                    1000.0, 3000.0, 10000.0,
                                                    30000.0],
                                         'svr__kernel': ['linear']},
                                        {'svr__C': [1.0, 3.0, 10.0, 30.0, 100.0,
                                                    300.0, 1000.0],
                                         'svr__gamma': [0.01, 0.03, 0.1, 0.3,
                                                        1.0, 3.0],
                                         'svr__kernel': ['rbf']}],
                   random_state=42, scoring='neg_root_mean_squared_error')

In [31]:
housing_predictions = rnd_search.predict(housing.iloc[:5])
housing_predictions[:5]

array([209417.16948572, 288832.42530059, 111878.05692933, 116799.7975926 ,
       235966.64457375])

In [32]:
housing_labels[:5].values

array([458300., 483800., 101700.,  96100., 361800.])

In [33]:
svr_rnd_search_rmse = -rnd_search.best_score_
svr_rnd_search_rmse

np.float64(85808.25708277174)

In [34]:
rnd_search.best_params_

{'svr__kernel': 'rbf', 'svr__gamma': 0.03, 'svr__C': 1000.0}

## Exercise 3

We use a `SelectFromModel` to select only the most important attributes before
doing the learning.

In [41]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.feature_selection import SelectFromModel

# SelectFromModel example https://scikit-learn.org/stable/modules/feature_selection.html#select-from-model
selector_pipeline = Pipeline([
    ("preprocessing", preprocessing),
    ("selection", SelectFromModel(RandomForestRegressor(random_state=42), threshold=0.005)),
    ("svr", SVR(C=rnd_search.best_params_['svr__C'],
                kernel=rnd_search.best_params_['svr__kernel'],
                gamma=rnd_search.best_params_['svr__gamma'])),
])
selector_pipeline.fit(housing.iloc[:5000], housing_labels.iloc[:5000])


array([212500., 288100., 114700., 122000., 240900.])

In [42]:
housing_predictions = selector_pipeline.predict(housing.iloc[:5])
housing_predictions[:5].round(-2)

array([212500., 288100., 114700., 122000., 240900.])

In [43]:
from sklearn.model_selection import cross_val_score


selector_rmses = -cross_val_score(selector_pipeline, housing[:5000], housing_labels[:5000], scoring='neg_root_mean_squared_error', cv=3)
selector_rmses

array([87335.41432054, 87479.52656474, 83035.66918013])

In [44]:
pd.Series(selector_rmses).describe()

count        3.000000
mean     85950.203355
std       2525.088945
min      83035.669180
25%      85185.541750
50%      87335.414321
75%      87407.470443
max      87479.526565
dtype: float64

## Exercise 4

In [58]:
from sklearn.base import check_array, check_is_fitted
from sklearn.neighbors import KNeighborsRegressor

# Custom transformer to estimate values based on KNN
class KnnTransformer(BaseEstimator, TransformerMixin):
    def __init__(self, input_features=['latitude', 'longitude'], n_neighbors=5):
        self.n_neighbors = n_neighbors
        self.input_features = input_features

    def fit(self, X, y):
        X2 = X[self.input_features]
        X2 = check_array(X2) # ensure X is array-like
        knn_regressor = KNeighborsRegressor(n_neighbors=self.n_neighbors)
        knn_regressor.fit(X2, y)
        self.knn_regressor_ = knn_regressor
        return self

    def transform(self, X):
        check_is_fitted(self)
        X2 = X[self.input_features]
        X2 = check_array(X2)
        assert self.knn_regressor_ is not None, "The model has not been fitted yet."

        y_pred = self.knn_regressor_.predict(X2)
        return y_pred.reshape(-1, 1) # reshape to 2D array

    def get_feature_names_out(self, names=None):
        return [f"nearest_{self.n_neighbors}_neighbors"]


In [61]:
preprocessing2 = ColumnTransformer([
        ("bedrooms", ratio_pipeline(), ["total_bedrooms", "total_rooms"]),
        ("rooms_per_house", ratio_pipeline(), ["total_rooms", "households"]),
        ("people_per_house", ratio_pipeline(), ["population", "households"]),
        ("log", log_pipeline, ["total_bedrooms", "total_rooms", "population",
                            "households", "median_income"]),
        ("geo", cluster_simil, ["latitude", "longitude"]),
        ("cat", cat_pipeline, make_column_selector(dtype_include="object")),
        ("geo_knn", KnnTransformer(input_features=['latitude', 'longitude'], n_neighbors=5), ["latitude", "longitude"]),
    ],
    remainder=default_num_pipeline)

# Fit and transform - get the actual data, not just shape
housing2 = preprocessing2.fit_transform(housing, housing_labels)

# Get feature names
features = preprocessing2.get_feature_names_out()

# Create DataFrame to inspect
df = pd.DataFrame(housing2, columns=features)
df.head()

bedrooms__ratio  rooms_per_house__ratio  people_per_house__ratio  \
0         1.846624               -0.866027                -0.330204   
1        -0.508121                0.024550                -0.253616   
2        -0.202155               -0.041193                -0.051041   
3        -0.149006               -0.034858                -0.141475   
4         0.963208               -0.666554                -0.306148   

   log__total_bedrooms  log__total_rooms  log__population  log__households  \
0             1.324114          0.637892         0.456906         1.310369   
1            -0.252671         -0.063576        -0.711654        -0.142030   
2            -0.925266         -0.859927        -0.941997        -0.913030   
3             0.952773          0.943475         0.670700         0.925373   
4             1.437622          1.003590         0.719093         1.481464   

   log__median_income  geo__Cluster 0 similarity  geo__Cluster 1 similarity  \
0           -1.071522               4.581829e-01               1.241847e-14   
1            1.194712               6.511495e-10               9.579596e-01   
2           -0.756981               3.432506e-01               4.261141e-15   
3           -0.912253               2.244844e-15               2.704823e-01   
4            0.034537               1.090228e-11               9.422206e-01   

   ...  geo__Cluster 7 similarity  geo__Cluster 8 similarity  \
0  ...               9.770322e-01               2.382191e-08   
1  ...               1.260964e-13               1.103491e-01   
2  ...               7.303265e-01               2.508224e-08   
3  ...               5.201263e-20               1.712982e-03   
4  ...               1.048030e-15               2.568824e-02   

   geo__Cluster 9 similarity  cat__ocean_proximity_<1H OCEAN  \
0               3.819126e-18                             0.0   
1               3.547610e-01                             1.0   
2               2.669659e-18                             0.0   
3               8.874598e-01                             0.0   
4               5.279506e-01                             0.0   

   cat__ocean_proximity_INLAND  cat__ocean_proximity_ISLAND  \
0                          0.0                          0.0   
1                          0.0                          0.0   
2                          1.0                          0.0   
3                          1.0                          0.0   
4                          0.0                          0.0   

   cat__ocean_proximity_NEAR BAY  cat__ocean_proximity_NEAR OCEAN  \
0                            1.0                              0.0   
1                            0.0                              0.0   
2                            0.0                              0.0   
3                            0.0                              0.0   
4                            0.0                              1.0   

   geo_knn__nearest_5_neighbors  remainder__housing_median_age  
0                      465660.4                       1.861119  
1                      366500.0                       0.907630  
2                      108880.0                       0.351428  
3                      106320.0                      -0.919891  
4                      319660.0                       0.589800  

[5 rows x 25 columns]